name: ai_text_extracter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  google_mlkit_text_recognition: ^0.13.0
  get: ^4.6.6
  google_ml_kit: ^0.18.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.3.1
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
